### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pirosikick** [pirosikick/ava2jest#1]
- [x] test.cb
- [x] context
  - [x] insert `let context = {}` after last `import ... from "..."`
- [x] test.skip, test.only, test.serial
- [x] import tt from 'ava'
- [x] t.log => console.log
- [x] t.plan => expect.assertions
- [x] transform assertions only in `test(...)`
- [x] `test(anotherVar => { ... })`
- [x] `done` is already used in `test.cb`
- [x] transform test.skip if t.pass is found in implementation

----✄----

- [ ] refactoring
  - [ ] use `find(type, filterOptions)`
  - [ ] put 2 params assertion transform in one
- [ ] README
  - [ ] USAGE
  - [ ] Add badges
